#!/usr/bin/env bash
# hub-workspace reference · vendor web fonts so no leaf fetches anything external.
# Pulls the Google Fonts CSS for the families you name, keeps the latin subsets only, downloads
# each woff2 into site/fonts/, and writes site/fonts/fonts.css with local url()s. Idempotent.
#   tools/vendor-fonts.sh 'family=Source+Serif+4:wght@400;600&family=Inter:wght@400;600'
# (The reference hub itself uses system font stacks and vendors nothing.)
set -euo pipefail
HUB="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HUB/site/fonts"
FAMILIES="${1:?usage: tools/vendor-fonts.sh '<google-fonts css2 family query>'}&display=swap"
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
mkdir -p "$OUT"
TMP="$(mktemp)"
curl -sS -A "$UA" "https://fonts.googleapis.com/css2?$FAMILIES" -o "$TMP"
python3 - "$TMP" "$OUT" <<'EOF'
import re, sys, os, subprocess, hashlib
src, out = sys.argv[1], sys.argv[2]
css = open(src).read()
blocks = re.findall(r'/\* (\w[\w-]*) \*/\n(@font-face \{.*?\})', css, flags=re.S)
kept = []
for subset, block in blocks:
    if subset != 'latin': continue
    fam = re.search(r"font-family: '([^']+)'", block).group(1)
    style = re.search(r'font-style: (\w+)', block).group(1)
    weight = re.search(r'font-weight: (\d+)', block).group(1)
    url = re.search(r'url\((https://fonts\.gstatic\.com/[^)]+)\)', block).group(1)
    name = re.sub(r'[^A-Za-z0-9]+', '-', fam).strip('-').lower() + f'-{weight}-{style}.woff2'
    dest = os.path.join(out, name)
    if not os.path.exists(dest):
        subprocess.run(['curl', '-sS', url, '-o', dest], check=True)
    kept.append(block.replace(url, './' + name))
header = '/* GENERATED by tools/vendor-fonts.sh — latin subsets. Do not edit; re-run the script. */\n'
open(os.path.join(out, 'fonts.css'), 'w').write(header + '\n'.join(kept) + '\n')
print(f'{len(kept)} font faces vendored into {out}')
EOF
rm -f "$TMP"
if grep -q 'https://' "$OUT/fonts.css"; then echo "FAIL: external url left in fonts.css" >&2; exit 1; fi
echo "fonts dir size: $(du -sh "$OUT" | cut -f1)"
