#!/usr/bin/env bash
# 3PT · vendor the design-system direction fonts so no leaf fetches anything external.
# Pulls the Google Fonts CSS for the six families the design-system leaf proposes, keeps the
# latin subsets only, downloads each woff2 into site/fonts/, and writes site/fonts/directions.css
# with local url()s. Re-run if the family list in this file changes. Idempotent.
set -euo pipefail
HUB="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HUB/site/fonts"
FAMILIES='family=Familjen+Grotesk:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&family=Instrument+Serif:ital@0;1&family=Instrument+Sans:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap'
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
mkdir -p "$OUT"
TMP="$(mktemp)"
curl -sS -A "$UA" "https://fonts.googleapis.com/css2?$FAMILIES" -o "$TMP"
python3 - "$TMP" "$OUT" <<'EOF'
import re, sys, os, subprocess, hashlib
src, out = sys.argv[1], sys.argv[2]
css = open(src).read()
blocks = re.findall(r'/\* (\w[\w-]*) \*/\n(@font-face \{.*?\})', css, flags=re.S)
kept = []
for subset, block in blocks:
    if subset != 'latin': continue
    fam = re.search(r"font-family: '([^']+)'", block).group(1)
    style = re.search(r'font-style: (\w+)', block).group(1)
    weight = re.search(r'font-weight: (\d+)', block).group(1)
    url = re.search(r'url\((https://fonts\.gstatic\.com/[^)]+)\)', block).group(1)
    name = re.sub(r'[^A-Za-z0-9]+', '-', fam).strip('-').lower() + f'-{weight}-{style}.woff2'
    dest = os.path.join(out, name)
    if not os.path.exists(dest):
        subprocess.run(['curl', '-sS', url, '-o', dest], check=True)
    kept.append(block.replace(url, './' + name))
header = '/* GENERATED by hub/tools/vendor-fonts.sh — latin subsets of the design-system direction fonts. Do not edit; re-run the script. */\n'
open(os.path.join(out, 'directions.css'), 'w').write(header + '\n'.join(kept) + '\n')
print(f'{len(kept)} font faces vendored into {out}')
EOF
rm -f "$TMP"
if grep -q 'https://' "$OUT/directions.css"; then echo "FAIL: external url left in directions.css" >&2; exit 1; fi
echo "fonts dir size: $(du -sh "$OUT" | cut -f1)"
